### ISSUE TITLE
udl_server not starting?

### ISSUE THREAD

**Issue by RoganDawes** [shuckc/pialarm#4]
I've moved from my Linux laptop to a Mac, and now I find that udl_server is not starting. The console runs, but no listening port is opened, and no output from the udl_server routine appears.

Seems like the problem is the "*" for addresses to bind to, it seems to take a long time to return in `asyncio.start_server`. (I actually never waited long enough). It works fine with "localhost".

**Comment by shuckc** [comment]
I think this is one of the things asyncio doesn't fiux cross-platform out of the box. I've got mac's here for work, I will see if it's easy to patch.

**Comment by shuckc** [comment]
I wasn't able to reproduce this, it started up OK on my mac pretty much instantly.
